# Generated by Django 5.1.3 on 2025-05-25 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('BapGo', '0001_initial'),
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ROOMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=1)),
                ('search_area', models.CharField(max_length=10)),
                ('search_keyword', models.CharField(max_length=10)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('place_purpose', models.CharField(max_length=10)),
                ('add_who', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.member')),
                ('place_00_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms_place_00', to='BapGo.google_api_te')),
                ('place_01_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms_place_01', to='BapGo.google_api_te')),
                ('place_02_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms_place_02', to='BapGo.google_api_te')),
                ('place_03_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms_place_03', to='BapGo.google_api_te')),
                ('place_04_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms_place_04', to='BapGo.google_api_te')),
                ('place_05_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms_place_05', to='BapGo.google_api_te')),
                ('place_06_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms_place_06', to='BapGo.google_api_te')),
                ('place_07_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms_place_07', to='BapGo.google_api_te')),
                ('place_08_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms_place_08', to='BapGo.google_api_te')),
                ('place_09_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms_place_09', to='BapGo.google_api_te')),
            ],
        ),
    ]
