# Generated by Django 5.1.1 on 2024-11-24 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('pw', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('nicname', models.CharField(max_length=20)),
                ('mdate', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
