# Generated by Django 5.1.3 on 2025-04-12 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bapgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=20)),
                ('rate', models.FloatField(default=0)),
                ('rcount', models.IntegerField(default=0)),
                ('status', models.CharField(max_length=15)),
                ('purl', models.TextField()),
                ('Bdate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='KAKAO_API_TE',
            fields=[
                ('kakao_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('place_name', models.CharField(max_length=255)),
                ('road_address_name', models.CharField(blank=True, max_length=500, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rdate', models.DateField()),
                ('rrate', models.FloatField(default=0)),
                ('rtext', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GOOGLE_API_TE',
            fields=[
                ('google_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('open_now', models.BooleanField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('price_level', models.IntegerField(blank=True, null=True)),
                ('user_ratings_total', models.IntegerField(blank=True, null=True)),
                ('pictures', models.JSONField(blank=True, null=True)),
                ('reviews', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kakao_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_data', to='BapGo.kakao_api_te')),
            ],
        ),
    ]
