# Generated by Django 5.1.1 on 2024-11-24 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BapGo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bapgo',
            name='rate',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='rrate',
            field=models.FloatField(default=0),
        ),
    ]
