# Generated by Django 5.1.3 on 2025-01-19 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BapGo', '0002_alter_bapgo_rate_alter_reviews_rrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='bapgo',
            name='Bdate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
