# Generated by Django 5.1.3 on 2025-03-09 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BapGo", "0003_bapgo_bdate"),
    ]

    operations = [
        migrations.CreateModel(
            name="KAKAO_API_TE",
            fields=[
                (
                    "kakao_id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("place_name", models.CharField(max_length=255)),
                (
                    "road_address_name",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
