# Generated by Django 5.1.3 on 2025-05-25 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ROOM_DETAIL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_status', models.IntegerField()),
                ('reaction_00', models.IntegerField()),
                ('reaction_01', models.IntegerField()),
                ('reaction_02', models.IntegerField()),
                ('reaction_03', models.IntegerField()),
                ('reaction_04', models.IntegerField()),
                ('reaction_05', models.IntegerField()),
                ('reaction_06', models.IntegerField()),
                ('reaction_07', models.IntegerField()),
                ('reaction_08', models.IntegerField()),
                ('reaction_09', models.IntegerField()),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.rooms')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.member')),
            ],
        ),
    ]
